const dummyNotification = [
  {
    picture: "../../assets/user-demo.png",
    name: "Alice Johnson",
    notification_type: "Got an email",
    notification_body: "You have received a new email from your manager.",
    timestamp: "14:23, 2024-08-14",
  },
  {
    picture: "../../assets/user-demo.png",
    name: "Bob Smith",
    notification_type: "Create a new event",
    notification_body: "A new event has been created in your calendar.",
    timestamp: "09:45, 2024-08-13",
  },
  {
    picture: "../../assets/user-demo.png",
    name: "Carol Williams",
    notification_type: "Someone mentioned you",
    notification_body: "You were mentioned in a comment on the project.",
    timestamp: "11:30, 2024-08-12",
  },
  {
    picture: "../../assets/user-demo.png",
    name: "David Brown",
    notification_type: "Support ticket",
    notification_body: "A new support ticket has been assigned to you.",
    timestamp: "15:00, 2024-08-11",
  },
  {
    picture: "../../assets/user-demo.png",
    name: "Eve Davis",
    notification_type: "Got an email",
    notification_body: "You have received a new email from HR.",
    timestamp: "16:25, 2024-08-10",
  },
  {
    picture: "../../assets/user-demo.png",
    name: "Frank Miller",
    notification_type: "Create a new event",
    notification_body: "A team meeting has been scheduled.",
    timestamp: "08:00, 2024-08-09",
  },
  {
    picture: "../../assets/user-demo.png",
    name: "Grace Wilson",
    notification_type: "Someone mentioned you",
    notification_body: "You were mentioned in a task update.",
    timestamp: "10:15, 2024-08-08",
  },
  {
    picture: "../../assets/user-demo.png",
    name: "Henry Moore",
    notification_type: "Support ticket",
    notification_body: "A customer issue has been reported.",
    timestamp: "13:45, 2024-08-07",
  },
  {
    picture: "../../assets/user-demo.png",
    name: "Ivy Taylor",
    notification_type: "Got an email",
    notification_body: "You have received a new email from the client.",
    timestamp: "12:30, 2024-08-06",
  },
  {
    picture: "../../assets/user-demo.png",
    name: "Jack Anderson",
    notification_type: "Create a new event",
    notification_body: "A workshop has been added to your schedule.",
    timestamp: "09:00, 2024-08-05",
  },
  {
    picture: "../../assets/user-demo.png",
    name: "Kim White",
    notification_type: "Someone mentioned you",
    notification_body: "You were mentioned in the company newsletter.",
    timestamp: "11:45, 2024-08-04",
  },
  {
    picture: "../../assets/user-demo.png",
    name: "Leo Harris",
    notification_type: "Support ticket",
    notification_body: "A support ticket needs your attention.",
    timestamp: "14:10, 2024-08-03",
  },
  {
    picture: "../../assets/user-demo.png",
    name: "Mia Clark",
    notification_type: "Got an email",
    notification_body: "You have received a new email from your team lead.",
    timestamp: "10:05, 2024-08-02",
  },
  {
    picture: "../../assets/user-demo.png",
    name: "Noah Lewis",
    notification_type: "Create a new event",
    notification_body: "A conference call has been scheduled.",
    timestamp: "13:20, 2024-08-01",
  },
  {
    picture: "../../assets/user-demo.png",
    name: "Olivia Walker",
    notification_type: "Someone mentioned you",
    notification_body: "You were mentioned in the project discussion.",
    timestamp: "15:35, 2024-07-31",
  },
  {
    picture: "../../assets/user-demo.png",
    name: "Paul Young",
    notification_type: "Support ticket",
    notification_body: "A new bug report has been submitted.",
    timestamp: "08:50, 2024-07-30",
  },
  {
    picture: "../../assets/user-demo.png",
    name: "Quinn Martinez",
    notification_type: "Got an email",
    notification_body: "You have received a new email from your supervisor.",
    timestamp: "17:15, 2024-07-29",
  },
];

export default dummyNotification;
